#version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: javi98/python-openai-generator-srt:1.0.1
    container_name: python-openai-generator-srt-app
    tty: true
    stdin_open: true
    restart: unless-stopped
    #command: python3 /code/app/app/main.py
    volumes:
      - ./:/code/app
      - ./data/audios:/code/app/data/audios
      - ./data/videos:/code/app/data/videos
      - ./data/subtitles:/code/app/data/subtitles
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  python-openai-generator-srt:
    driver: bridge

